name: Training 
type: theme
description: 'Training Theme new for My Website.'
package: Other
core: 8.x
libraries:
    - taining/global-styling
base theme:
    classy
regions:
    branding: Branding
    navigation: Main navigation
    search: Search
    featured: Featured
    content: Content
    right_sidebar: Right sidebar
    footer_first: Footer First
    footer_second: Footer Second
    footer_third: Footer Third
    footer_bottom: Footer Bottom